apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
items:

- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      v1.min.io/tenant: s3demo
    name: s3demo-user-0
  immutable: true
  type: Opaque
  stringData:
    CONSOLE_ACCESS_KEY: 9be00caf37a295f6873f6fb705896e00
    CONSOLE_SECRET_KEY: 6a23a7cf7ea31a4622815f231c0d6b4d

- apiVersion: v1
  immutable: true
  kind: Secret
  metadata:
    labels:
      v1.min.io/tenant: s3demo
    name: s3demo-secret
  type: Opaque
  data:
    accesskey: ""
    secretkey: ""

- apiVersion: v1
  stringData:
    config.env: |
      export MINIO_BROWSER="on"
      export MINIO_ROOT_USER="c17479cb7be17d0a42c0c4d130fef0af"
      export MINIO_ROOT_PASSWORD="f8f48578f8fb6a757e1e85584c37fb2a"
      export MINIO_STORAGE_CLASS_STANDARD="EC:8"
      export MINIO_HTTP_TRACE="/export/trace.log"
  kind: Secret
  metadata:
    labels:
      v1.min.io/tenant: s3demo
    name: s3demo-env-configuration
  type: Opaque

- kind: Service
  apiVersion: v1
  metadata:
    name: ui-android
  spec:
    ports:
      - name: http
        targetPort: 8080
        port: 8080
        protocol: TCP
    selector:
      app.kubernetes.io/name: ui-android

- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: ui-android
  spec:
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/name: ui-android
    template:
      metadata:
        annotations:
        labels:
          app.kubernetes.io/name: ui-android
      spec:
        automountServiceAccountToken: false
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        containers:
          - name: ui-android
            securityContext:
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000
            image: "ghcr.io/egeneralov/minio-public-ui/minio-public-ui:1.0.7"
            imagePullPolicy: "IfNotPresent"
            ports:
              - name: http
                containerPort: 8080
                protocol: TCP
            command:
              - /go/bin/minio-public-ui
              - -url
              - http://minio
              - -eTag
              - -lastModified
              - -ownerDisplayName
              - -size
              - -storageClass
              - -path
              - /ui/android/
              - -bucket
              - android

- apiVersion: minio.min.io/v2
  kind: Tenant
  metadata:
    generation: 1
    name: s3demo
  scheduler:
    name: ""
  spec:
    configuration:
      name: s3demo-env-configuration
    credsSecret:
      name: s3demo-secret
    exposeServices:
      console: false
      minio: false
    image: minio/minio:RELEASE.2022-10-29T06-21-33Z
    mountPath: /export
    features:
      domains:
        console: https://s3-console.generalov.org
        minio:
          - https://s3.generalov.org
    buckets:
      - name: "android"
        objectLock: true
        region: "us-east-1" 
    pools:
    - name: mobile
      resources:
        requests:
          cpu: "1"
          memory: 2Gi
      servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: "1099511627776"
          storageClassName: nvme
    prometheus:
      diskCapacityGB: 1
      resources: {}
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      storageClassName: nvme
    requestAutoCert: false
    users:
      - name: s3demo-user-0
    logging:
      anonymous: true
      json: true
      quiet: false

- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: 100m
    labels:
      app: minio
    name: minio
  spec:
    ingressClassName: nginx
    rules:
    - host: s3.generalov.org
      http:
        paths:
        - backend:
            service:
              name: minio
              port:
                number: 80
          path: /
          pathType: Prefix
        - backend:
            service:
              name: ui-android
              port:
                number: 8080
          path: /ui/android/
          pathType: Prefix
    tls:
    - hosts:
      - s3.generalov.org
      secretName: s3.generalov.org

- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: 100m
    labels:
      app: minio
    name: minio-console
  spec:
    ingressClassName: nginx
    rules:
    - host: s3-console.generalov.org
      http:
        paths:
        - backend:
            service:
              name: s3demo-console
              port:
                number: 9090
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - s3-console.generalov.org
      secretName: s3-console.generalov.org
